#!/usr/bin/env python3
"""
Generate browser-extension/detectors.js from src/detection/library.py.

The Python library is the single source of truth for built-in detectors; the extension
loads the generated file (importScripts) so both sides detect the same things.

  python scripts/build_extension_detectors.py          # write the file
  python scripts/build_extension_detectors.py --check  # exit 1 if it is out of date (CI)
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from src.detection.library import DETECTORS, KEYWORD_BOOST, KEYWORD_WINDOW, LEGACY_ALIASES  # noqa: E402

OUT = ROOT / "browser-extension" / "detectors.js"
FIELDS = ("name", "pattern", "ignore_case", "group", "validator", "keywords", "require_keyword",
          "prefilter", "generic", "severity", "confidence", "category", "description")


def render() -> str:
    detectors = []
    for d in DETECTORS:
        re.compile(d["pattern"])  # must stay valid Python regex
        detectors.append({k: d[k] for k in FIELDS if k in d})
    body = json.dumps(detectors, indent=2, ensure_ascii=True)
    return (
        "// GENERATED by scripts/build_extension_detectors.py from src/detection/library.py.\n"
        "// Do not edit by hand: change the Python library and re-run the script.\n"
        f"const TRON_KEYWORD_WINDOW = {KEYWORD_WINDOW};\n"
        f"const TRON_KEYWORD_BOOST = {KEYWORD_BOOST};\n"
        f"const TRON_LEGACY_ALIASES = {json.dumps(LEGACY_ALIASES, indent=2, sort_keys=True)};\n"
        f"const TRON_DETECTORS = {body};\n"
    )


def main():
    content = render()
    if "--check" in sys.argv:
        current = OUT.read_text() if OUT.exists() else ""
        if current != content:
            print(f"{OUT.relative_to(ROOT)} is out of date; run scripts/build_extension_detectors.py")
            sys.exit(1)
        print("detectors.js is up to date")
        return
    OUT.write_text(content)
    print(f"wrote {OUT.relative_to(ROOT)} ({len(DETECTORS)} detectors)")


if __name__ == "__main__":
    main()
